apiVersion: 1

datasources:
  - name: InfluxDB-EspVRna
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ProjecteEspVRna
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    editable: true
    isDefault: true
    uid: influxdb-espvrna
